Load rails environment first in test
This prevents the following error with capybara:

/usr/local/bundle/gems/capybara-3.29.0/lib/capybara/rails.rb:7:in `block (2 levels) in <top (required)>': undefined method `application' for Rails:Module (NoMethodError)